from .module.node import NODE_CLASS_MAPPINGS as NODE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as DISPLAY_MAPPINGS
from .module.video import NODE_CLASS_MAPPINGS as VIDEO_NODE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as VIDEO_DISPLAY_MAPPINGS

# 合并所有节点映射
NODE_CLASS_MAPPINGS = {**NODE_MAPPINGS, **VIDEO_NODE_MAPPINGS}
NODE_DISPLAY_NAME_MAPPINGS = {**DISPLAY_MAPPINGS, **VIDEO_DISPLAY_MAPPINGS}

# 导出节点映射供 ComfyUI 加载
__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']

# 插件信息
WEB_DIRECTORY = "./web"
